model_params:
  source_path: x:\_ai\_my\dreamer1
  model_path: x:\_ai\_my\dreamer1-out
  eval: false
  sh_degree: 1
  load_skymask: true
#  load_mask: true
  resolution: 1
#  N_random_init_pts: 200
  spatial_scaling_lr_mult: 20

  dreamer_calibs: true

#progress_params:
#  save_gaussians_iterations: [7000]
#  save_checkoint_iterations: [7000]

optimization_params:

  random_background: true

  skysphere_loss: true
  sky_depth_loss: true
#  silhouette_loss: true


  kl_threshold: 0.4

  iterations: 1000
  densify_until_iter: 5000

  densification_interval: 2500

#  c2f: true
#  c2f_max_sigma: 30

  skysphere_radius: 300