model_params:
  source_path: x:\_ai\_demos\_gsplat\_datasets\youtube05\towel
  model_path: x:\_ai\_demos\_gsplat\_datasets\youtube05\towel-my-111-c2f-start30x1
  eval: false
  sh_degree: 1
#  load_skymask: true
#  load_mask: true
  resolution: 1
#  N_random_init_pts: 200
#  spatial_scaling_lr_mult: 0.5

progress_params:
  #load_gaussians_path: x:\_ai\_demos\_gsplat\_datasets\youtube02\towel-my-111-c2f-start30\point_cloud\iteration_25000\point_cloud.ply
  load_checkoint_path: x:\_ai\_demos\_gsplat\_datasets\youtube05\towel-my-111-c2f-start30\chkpnt7000.pth

optimization_params:

  random_background: true

#  skysphere_loss: true
#  sky_depth_loss: true
#  silhouette_loss: true

  kl_threshold: 0.4

  iterations: 25000
  densify_until_iter: 22500

  densification_interval: 200

#  c2f: true
#  c2f_max_sigma: 1.5