model_params:
  source_path: x:\_ai\_demos\_gsplat\_datasets\mip360\kitchen
  model_path: x:\_ai\_demos\_gsplat\_datasets\mip360\kitchen-lego-only
  eval: false
  sh_degree: 3
  load_mask: true
  resolution: 2
  N_random_init_pts: 200

optimization_params:

  random_background: true
  skysphere_radius: 30
  sky_depth_loss: true
  silhouette_loss: true

  kl_threshold: 0.2

  iterations: 25000
  densify_until_iter: 22500

  densification_interval: 200

  c2f: true
