model_params:
  source_path: x:\_ai\_demos\_gsplat\_datasets\segment-102751
  model_path: x:\_ai\_demos\_gsplat\_datasets\segment-102751-7000
  eval: false
  sh_degree: 0
  load_skymask: true
#  load_mask: true
  N_random_init_pts: 2000
  spatial_scaling_lr_mult: 0.2

  resolution_scales: [1, 0.33, 0.1]

#progress_params:
#  save_gaussians_iterations: [7000]
#  save_checkoint_iterations: [7000]

optimization_params:

  random_background: true

  skysphere_loss: true
  sky_depth_loss: true

  kl_threshold: 0.4

#  smallest_point_divider: 25000

#  semitransparent_loss: true

  iterations: 25000

  densify_from_iter: 500
  densify_until_iter: 22500

  densification_interval: 100

  fft_loss: false
  fft_lowpass_sigma_initial: 0.5
  fft_lowpass_sigma_iter: 5000

  c2f_inflection_iteration: 7000
