model_params:
  source_path: x:\_ai\_demos\_gsplat\_datasets\segment-102751
  model_path: x:\_ai\_demos\_gsplat\_datasets\segment-102751-7000
  eval: false
  sh_degree: 1
  load_skymask: true
#  load_mask: true
  resolution: 1
  spatial_scaling_lr_mult: 10.0
#  N_random_init_pts: 200

progress_params:
  load_checkoint_path: X:\_ai\_demos\_gsplat\_datasets\segment-102751-7000\chkpnt7000.pth


optimization_params:

  random_background: true

  skysphere_loss: true
  sky_depth_loss: true
#  silhouette_loss: true


  kl_threshold: 0.05

  iterations: 25000
  densify_until_iter: 22500

  densification_interval: 150

#  c2f: true
#  c2f_max_sigma: 30